services:
  db:
    image: postgres:14
    env_file:
      - ./backend/.env
    healthcheck:
      test:
        - CMD-SHELL
        - 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    volumes:
      - group-project:/var/lib/postgresql/data
      - ./backend/db:/docker-entrypoint-initdb.d
  web:
    image: node:lts
    user: 'node'
    working_dir: /repository/backend
    env_file: ./backend/.env
    environment:
      - NODE_ENV=development
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3001'
    volumes:
      - ./:/repository
    command: 'npm start'
volumes:
  group-project: